name: 2022.3.61f1-playmode

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  editor-tests:
    uses: ./.github/workflows/main.yml
    with:
      projectPath: './'
      unityVersion: '2022.3.61f1'
      testMode: 'playmode'
    secrets: inherit