name: Editor Tests

on:
  workflow_call:
    inputs:
      projectPath:
        required: true
        type: string
      unityVersion:
        required: true
        type: string
      testMode:
        required: true
        type: string
    secrets:
      UNITY_LICENSE:
        required: true
      UNITY_EMAIL:
        required: true
      UNITY_PASSWORD:
        required: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    name: ${{ inputs.unityVersion }} ${{ inputs.testMode }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
      - uses: actions/cache@v4
        with:
          path: |
            ${{ inputs.projectPath }}/Library
            ~/.cache/unity3d
          key: Library-${{ inputs.unityVersion }}-${{ inputs.testMode }}-${{ matrix.os }}
      - uses: game-ci/unity-test-runner@v4
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ inputs.projectPath }}
          unityVersion: ${{ inputs.unityVersion }}
          testMode: ${{ inputs.testMode }}
          artifactsPath: ${{ inputs.testMode }}-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ inputs.unityVersion }} ${{ inputs.testMode }} Test Results